export const FETCH_LINE_PRODUCTS = 'FETCH_LINE_PRODUCTS';
export const ADD_LINE_PRODUCT = 'ADD_LINE_PRODUCT';
export const UPDATE_LINE_PRODUCT = 'UPDATE_LINE_PRODUCT';
export const DELETE_LINE_PRODUCT = 'DELETE_LINE_PRODUCT';
export const EDIT_LINE_PRODUCT = 'EDIT_LINE_PRODUCT';

export const FETCH_DETAIL_LINE_PRODUCTS = 'FETCH_DETAIL_LINE_PRODUCTS';

export const FETCH_LINE_PRODUCTS_NEW = 'FETCH_LINE_PRODUCTS_NEW';