export const FETCH_ORDER_SUPPLY = 'FETCH_ORDER_SUPPLY';
export const ADD_ORDER_SUPPLY = 'ADD_ORDER_SUPPLY';
export const UPDATE_ORDER_SUPPLY = 'UPDATE_ORDER_SUPPLY';
export const DELETE_ORDER_SUPPLY = 'DELETE_ORDER_SUPPLY';