export const FETCH_PROMOTION = 'FETCH_PROMOTION';
export const ADD_PROMOTION = 'ADD_PROMOTION';
export const UPDATE_PROMOTION = 'UPDATE_PROMOTION';
export const DELETE_PROMOTION = 'DELETE_PROMOTION';
export const EDIT_PROMOTION = 'EDIT_PROMOTION';