export const FETCH_SHIPPER = 'FETCH_SHIPPER';
export const ADD_SHIPPER = 'ADD_SHIPPER';
export const UPDATE_SHIPPER = 'UPDATE_SHIPPER';
export const DELETE_SHIPPER = 'DELETE_SHIPPER';
export const EDIT_SHIPPER = 'EDIT_SHIPPER';