export const FETCH_SHIPPING_COMPANY = 'FETCH_SHIPPING_COMPANY';
export const ADD_SHIPPING_COMPANY = 'ADD_SHIPPING_COMPANY';
export const UPDATE_SHIPPING_COMPANY = 'UPDATE_SHIPPING_COMPANY';
export const DELETE_SHIPPING_COMPANY = 'DELETE_SHIPPING_COMPANY';
export const EDIT_SHIPPING_COMPANY = 'EDIT_SHIPPING_COMPANY';